---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nodejs-helloworld
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
