apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-helloworld
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32121
  selector:
    app: nodejs-helloworld
